[tools]
java = "temurin-25.0.3+9.0.LTS"
maven = "3.9.16"

[tool_alias.java.versions]
oracle = "oracle-25.0.3"
temurin = "temurin-25.0.3+9.0.LTS"

[tool_alias.maven.versions]
latest = "3.9.16"

[env]
_.path = [
    "/home/vscode/.local/share/mise/installs/java/latest/bin:/home/vscode/.local/share/mise/installs/maven/latest/bin",
]
JAVA_HOME = "/home/vscode/.local/share/mise/installs/java/latest"
M2_HOME = "/home/vscode/.local/share/mise/installs/maven/latest"

[tasks]
"git:init" = { run = "mise generate git-pre-commit --write --task=lint" }
"git:tag-patch" = { run = "./scripts/git-tagger.sh patch" }
"git:tag-custom" = { run = "./scripts/git-tagger.sh custom" }

"application:build" = { run = "./scripts/build-image.sh" }

"docs:serve-docs" = { run = "miniserve ./docs --index index.html -p 3001" }
"docs:serve-report-sast" = { run = "miniserve ./build/reports/sast --index index.html -p 3002" }
"docs:serve-checkstyle" = { run = "miniserve ./build/reports/checkstyle --index main.html -p 3003" }
"docs:serve-dependencies" = { run = "miniserve ./build/reports/dependency-check --index report.html -p 3004" }
"docs:serve-report-test" = { run = "miniserve ./build/reports/tests/test --index index.html -p 3005" }
"docs:serve-report-jacoco" = { run = "miniserve ./build/reports/jacoco --index index.html -p 3006" }

[hooks]
postinstall = "../.devcontainer/devopsmind/scripts/sync-env.sh"

[[watch_files]]
patterns = ["mise.toml"]
run = "../.devcontainer/devopsmind/scripts/sync-env.sh"
