services:
  devopsmind:
    image: mcr.microsoft.com/devcontainers/base:ubuntu26.04
    env_file:
      - /tmp/.env
    volumes:
      - ../../..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    network_mode: service:mysql
    environment:
      - TZ=America/Bogota
    depends_on:
      mysql:
        condition: service_healthy
      postgres-pgvector:
        condition: service_healthy
      mongo:
        condition: service_healthy
      vault:
        condition: service_healthy

  mysql:
    image: mysql:9.7.2
    container_name: srv-mysql
    hostname: service-devopsmind    
    restart: unless-stopped
    environment:
      TZ: America/Bogota
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_DATABASE_NAME}
      MYSQL_USER: ${DB_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ntw_ai
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_MYSQL_USERNAME}", "-p${DB_MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: srv-ui-phpmyadmin
    restart: unless-stopped
    environment:
      TZ: America/Bogota
      PMA_HOST: srv-mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - ntw_ai
    depends_on:
      mysql:
        condition: service_healthy

  postgres-pgvector:
    image: pgvector/pgvector:pg18
    container_name: srv-postgres
    restart: unless-stopped
    environment:
      TZ: America/Bogota
      POSTGRES_DB: ${DB_POSTGRES_VECTOR_NAME}
      POSTGRES_USER: ${DB_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/data
    networks:
      - ntw_ai
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POSTGRES_USERNAME} -d ${DB_POSTGRES_VECTOR_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: srv-ui-pgadmin
    restart: unless-stopped
    environment:
      TZ: America/Bogota
      PGADMIN_DEFAULT_EMAIL: ${DB_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PGADMIN_PASSWORD}
      PGADMIN_DISABLE_POSTGRES_USER_DETECTION: "true"
    ports:
      - "8082:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ntw_ai
    depends_on:
      postgres-pgvector:
        condition: service_healthy

  mongo:
    image: mongo:8.3.11
    container_name: srv-mongo
    restart: unless-stopped
    environment:
      TZ: America/Bogota
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_MONGO_INITIAL_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ntw_ai
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongo-express:
    image: mongo-express:latest
    container_name: srv-ui-mongo-express
    restart: unless-stopped
    environment:
      TZ: America/Bogota
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_MONGOEX_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_MONGOEX_ADMIN_PASSWROD}
      ME_CONFIG_MONGODB_SERVER: srv-mongo
      ME_CONFIG_MONGODB_PORT: 27017
    ports:
      - "8083:8081"
    networks:
      - ntw_ai
    depends_on:
      mongo:
        condition: service_healthy
  
  vault:
    image: openbao/openbao:latest
    container_name: srv-secret-manager
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      TZ: America/Bogota    
      BAO_DEV_ROOT_TOKEN_ID: ${TOKEN_SECRET_MANAGER}
      BAO_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://srv-secret-manager:8200
    volumes:
      - ./configs/openbao/config:/openbao/config
      - ./configs/openbao/data:/openbao/data
    networks:
      - ntw_ai
    healthcheck:
      test: ["CMD", "bao", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: srv-keycloak
    restart: always
    command: start-dev
    ports:
      - "8089:8080"
    environment:
      - TZ=America/Bogota    
      - KEYCLOAK_ADMIN=${AUTH_KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${AUTH_KEYCLOAK_ADMIN_PASSWORD}
      - KC_HEALTH_ENABLED=true
    networks:
      - ntw_ai
    volumes:
      - ./configs/keycloak/workshop-realm.json:/opt/keycloak/data/import/workshop-realm.json      
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080 && echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | grep -q '200 OK'"]
      interval: 10s
      timeout: 5s
      retries: 5
  alloy:
    image: grafana/alloy:latest
    container_name: srv-alloy
    restart: always
    ports:
      - "4317:4317"
      - "4318:4318"
      - "12345:12345"
    environment:
      TZ: America/Bogota 
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
      - /etc/alloy/config.alloy
      - --stability.level=experimental
    volumes:
      - vlm_devopsmind_logs:/var/log/spring/devopsmind:ro
      - ./configs/alloy/config.alloy:/etc/alloy/config.alloy:ro
    networks:
      - ntw_ai
  tempo:
    image: grafana/tempo:2.10.4
    container_name: srv-tempo
    restart: always    
    command: [ "-config.file=/etc/tempo.yaml" ]
    environment:
      TZ: America/Bogota     
    volumes:
      - ./configs/tempo/tempo.yaml:/etc/tempo.yaml:ro
    ports:
      - "3200:3200"   # Tempo UI/API
    networks:
      - ntw_ai 

  prometheus:
    image: prom/prometheus:latest
    container_name: srv-prometheus
    ports:
      - "9090:9090"
    environment:
      TZ: America/Bogota       
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./configs/prometheus/prometheus.dev.yml:/etc/prometheus/prometheus.yml
    networks:
      - ntw_ai
  loki:
    image: grafana/loki:latest
    container_name: srv-loki
    ports:
      - "3100:3100"
    environment:
      TZ: America/Bogota       
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - ntw_ai

  grafana:
    image: grafana/grafana:latest
    container_name: srv-grafana
    ports:
      - "3001:3000"
    environment:
      - TZ=America/Bogota
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_PASSWORD=${METRICS_GRAFANA_ADMIN_PASSWORD}
    networks:
      - ntw_ai
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml

volumes:
  mysql_data:
    driver: local
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  mongo_data:
    driver: local
  portainer_data:
  loki_data:
  grafana_data:
  vlm_devopsmind_logs:
    external: true
  vlm_mcp_server_logs:
    external: true

networks:
  ntw_ai:
    name: ntw_ai
    external: true
