spring:
  main:
    allow-bean-definition-overriding: true

  #cloud:
  #  vault:
  #    uri: http://${SECRET_MANAGER_HOSTNAME:srv-secret-manage}:8200
  #    authentication: TOKEN
  #    token: ${TOKEN_SECRET_MANAGER}
  #    kv:
  #      enabled: true
  #      backend: secret
  #      default-context: "kv/devopsmind"
  #      profile-separator: '/'
  #    fail-fast: true
  #    connection-timeout: 5000
  #    read-timeout: 15000
  #config:
  #  import: vault://
  jpa:
    hibernate:
      ddl-auto: validate
  storages:
    providers:
      mysql:
        url: jdbc:mysql://${DB_MYSQL_HOSTNAME:localhost}:3306/${DB_MYSQL_DATABASE_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: ${DB_MYSQL_USERNAME}
        password: ${DB_MYSQL_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          pool-name: devops-dev-hikari-pool
          minimum-idle: 2
          maximum-pool-size: 5
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
        flyway:
          locations: classpath:db/migration/mysql
          table: schema_version_mysql
      postgres:
        url: jdbc:postgresql://${DB_POSTGRES_HOSTNAME}:5432/${DB_POSTGRES_VECTOR_NAME:labmetricsia_vector_db}
        username: ${DB_POSTGRES_USERNAME}
        password: ${DB_POSTGRES_PASSWORD}
        hikari:
          pool-name: devops-dev-hikari-pool
          minimum-idle: 2
          maximum-pool-size: 5
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
        flyway:
          locations: classpath:db/migration/postgres
          table: schema_version_postgres
      mongodb:
        uri: mongodb://${DB_MONGO_ROOT_USERNAME:mongo}:${DB_MONGO_ROOT_PASSWORD:mongo}@${DB_MONGO_HOSTNAME:srv-mongo}:27017/${DB_MONGO_INITIAL_DB:chat_memory_db}?authSource=admin

  graphql:
    graphiql:
      enabled: true

  ai:
    vectorstore:
      pgvector:
        initialize-schema: false
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536

    ollama:
      base-url: http://${OLLAMA_SERVER_HOSTNAME:localhost}:11434
      chat:
        model: ${LLM_MODEL_NAME:llama3.2:1b}
        temperature: 0.7
