server:
  port: 8081 #

spring:
  ai:
    mcp:
      server:
        protocol: STREAMABLE
        name: mcp-server-host-telemetry
        version: 1.0.0
        type: SYNC
        instructions: "This streamable server provides real-detail host telemetry"
        resource-change-notification: true
        tool-change-notification: true
        prompt-change-notification: true
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 30s
